[package]
name = "spu_assembler"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.4.10", features = ["derive"] }
regex = "1.10.2"

#Enable high optimizations for libs.
[profile.dev.package."*"]
opt-level = 3

